name: Build and Push Monad Sandbox Image

on:
  push:
    branches:
      - 'main' # This is the branch that will trigger the build
  workflow_dispatch: # This allows you to manually run it from the GitHub website

jobs:
  build-and-push:
    runs-on: ubuntu-latest # GitHub provides this powerful virtual machine for free
    permissions:
      contents: read
      packages: write # This is critical. It grants the action permission to publish the package to your account

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive' # This is vital. It pulls in the 'monad' submodule code.

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/release.Dockerfile # We are telling it which Dockerfile to use
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/monad-sandbox:latest